[alembic]
script_location = migrations
# sqlalchemy.url will be used by env.py, keep it in sync with app config
sqlalchemy.url = sqlite:///project.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
# use stderr to ensure it works when sys isn't injected
args = (sys.stderr,)
level = NOTSET

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
